import Head from 'next/head'
import App from '../components/App'
import Features from '../components/Features'
import Mainbanner from '../components/Mainbanner'
import Subbanner from '../components/Subbanner'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Brands from '../components/Brands'
import Reviews from '../components/Reviews'
import Keyfeatures from '../components/Keyfeatures'
import KommunicateChat from '../components/KommunicateChat'

export default function Home() {
  return (
    <>
      <Head>
        <title>PayCube | Your Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Mainbanner></Mainbanner>
      <Subbanner></Subbanner>
      <Keyfeatures></Keyfeatures>
      <Features></Features>
      <Reviews></Reviews>
      <App></App>
      <Brands></Brands>
      <Footer></Footer>
      <KommunicateChat></KommunicateChat>
    </>
  )
}