import Head from 'next/head'
import App from '../components/app'
import Features from '../components/Features'
import Footer from '../components/Footer'
import Mainbanner from '../components/Mainbanner'
import Subbanner from '../components/Subbanner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>PayCube | Your Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mainbanner></Mainbanner>
      <Subbanner></Subbanner>
      <Features></Features>
      <App></App>
      <Footer></Footer>
    </div>
  )
}
