import Head from 'next/head'
import App from '../components/App'
import Features from '../components/Features'
import Mainbanner from '../components/Mainbanner'
import Subbanner from '../components/Subbanner'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Brands from '../components/Brands'
import Reviews from '../components/Reviews'
import Keyfeatures from '../components/Keyfeatures'
import KommunicateChat from '../components/KommunicateChat'
import Zoom from 'react-reveal/Zoom';

export default function Home() {
  return (
    <>
      <Head>
        <title>PayCube | Your Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Mainbanner></Mainbanner>
      <Zoom><Subbanner></Subbanner></Zoom>
      <Zoom><Keyfeatures></Keyfeatures></Zoom>
      <Zoom><Features></Features></Zoom>
      <Zoom><Reviews></Reviews></Zoom>
      <Zoom><App></App></Zoom>
      <Zoom><Brands></Brands></Zoom>
      <Footer></Footer>
      <KommunicateChat></KommunicateChat>
    </>
  )
}